name: Build
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env
      - name: install deps
        run: npm ci
      - name: Prisma generate
        run: npx prisma generate
      - name: Prisma migrate
        run: npx prisma migrate dev
      - name: Starting
        run: npm run start
