name: Build
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env
          print PORT=${{ secrets.PORT }} > .env
          print JWT_SECRET=${{ secrets.JWT_SECRET }} > .env
          print DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
      - name: Chekout
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci
      - name: Prisma generate
        run: npx prisma generate
      - name: Prisma migrate
        run: npx prisma migrate dev
      - name: Starting
        run: npm run server
