name: Pusher
on: 
    pull_request:
    push:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate dev
      - run: npm run server

